{% set name = "fett" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fett-{{ version }}.tar.gz
  sha256: 56912ad93cf537a450b4fb15ee97aedd97acf81a14e48375c523fffdeb182986

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - fett
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/i80and/fett
  summary: A fast indentation-preserving template engine.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tyrius02
    - maresb
